name = "ansiada"
description = "ANSI escape sequences"
version = "0.1.1"

licenses = "MIT"
authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

tags = ["ansi", "terminal"]
